// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "complementares.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



void
ComplementaresApp::AtividadeComplementar::operator>>= (cdrStream &_n) const
{
  RA >>= _n;
  _n.marshalString(descricao,0);
  categoria >>= _n;
  numeroHoras >>= _n;
  _n.marshalString(urlCertificado,0);

}

void
ComplementaresApp::AtividadeComplementar::operator<<= (cdrStream &_n)
{
  (::CORBA::Long&)RA <<= _n;
  descricao = _n.unmarshalString(0);
  (CategoriaComplementares&)categoria <<= _n;
  (::CORBA::Long&)numeroHoras <<= _n;
  urlCertificado = _n.unmarshalString(0);

}

ComplementaresApp::DepositoAtividades_ptr ComplementaresApp::DepositoAtividades_Helper::_nil() {
  return ::ComplementaresApp::DepositoAtividades::_nil();
}

::CORBA::Boolean ComplementaresApp::DepositoAtividades_Helper::is_nil(::ComplementaresApp::DepositoAtividades_ptr p) {
  return ::CORBA::is_nil(p);

}

void ComplementaresApp::DepositoAtividades_Helper::release(::ComplementaresApp::DepositoAtividades_ptr p) {
  ::CORBA::release(p);
}

void ComplementaresApp::DepositoAtividades_Helper::marshalObjRef(::ComplementaresApp::DepositoAtividades_ptr obj, cdrStream& s) {
  ::ComplementaresApp::DepositoAtividades::_marshalObjRef(obj, s);
}

ComplementaresApp::DepositoAtividades_ptr ComplementaresApp::DepositoAtividades_Helper::unmarshalObjRef(cdrStream& s) {
  return ::ComplementaresApp::DepositoAtividades::_unmarshalObjRef(s);
}

void ComplementaresApp::DepositoAtividades_Helper::duplicate(::ComplementaresApp::DepositoAtividades_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

ComplementaresApp::DepositoAtividades_ptr
ComplementaresApp::DepositoAtividades::_duplicate(::ComplementaresApp::DepositoAtividades_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

ComplementaresApp::DepositoAtividades_ptr
ComplementaresApp::DepositoAtividades::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


ComplementaresApp::DepositoAtividades_ptr
ComplementaresApp::DepositoAtividades::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

ComplementaresApp::DepositoAtividades_ptr
ComplementaresApp::DepositoAtividades::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_DepositoAtividades _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_DepositoAtividades* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_DepositoAtividades;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* ComplementaresApp::DepositoAtividades::_PD_repoId = "IDL:ComplementaresApp/DepositoAtividades:1.0";


ComplementaresApp::_objref_DepositoAtividades::~_objref_DepositoAtividades() {
  
}


ComplementaresApp::_objref_DepositoAtividades::_objref_DepositoAtividades(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::ComplementaresApp::DepositoAtividades::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
ComplementaresApp::_objref_DepositoAtividades::_ptrToObjRef(const char* id)
{
  if (id == ::ComplementaresApp::DepositoAtividades::_PD_repoId)
    return (::ComplementaresApp::DepositoAtividades_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::ComplementaresApp::DepositoAtividades::_PD_repoId))
    return (::ComplementaresApp::DepositoAtividades_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for ComplementaresApp::DepositoAtividades::cadastrarAtividade

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cComplementaresApp_mAtividadeComplementar
class _0RL_cd_8dfcf7274d2061b7_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_8dfcf7274d2061b7_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ComplementaresApp::AtividadeComplementar_var arg_0_;
  const ComplementaresApp::AtividadeComplementar* arg_0;
  ::CORBA::Boolean result;
};

void _0RL_cd_8dfcf7274d2061b7_00000000::marshalArguments(cdrStream& _n)
{
  (const ComplementaresApp::AtividadeComplementar&) *arg_0 >>= _n;

}

void _0RL_cd_8dfcf7274d2061b7_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new ComplementaresApp::AtividadeComplementar;
  (ComplementaresApp::AtividadeComplementar&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();

}

void _0RL_cd_8dfcf7274d2061b7_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_8dfcf7274d2061b7_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_8dfcf7274d2061b7_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_8dfcf7274d2061b7_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_8dfcf7274d2061b7_00000000* tcd = (_0RL_cd_8dfcf7274d2061b7_00000000*)cd;
  ComplementaresApp::_impl_DepositoAtividades* impl = (ComplementaresApp::_impl_DepositoAtividades*) svnt->_ptrToInterface(ComplementaresApp::DepositoAtividades::_PD_repoId);
  tcd->result = impl->cadastrarAtividade(*tcd->arg_0);


}

::CORBA::Boolean ComplementaresApp::_objref_DepositoAtividades::cadastrarAtividade(const ::ComplementaresApp::AtividadeComplementar& at)
{
  _0RL_cd_8dfcf7274d2061b7_00000000 _call_desc(_0RL_lcfn_8dfcf7274d2061b7_10000000, "cadastrarAtividade", 19);
  _call_desc.arg_0 = &(::ComplementaresApp::AtividadeComplementar&) at;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for ComplementaresApp::DepositoAtividades::contarHorasCadastradas

// Proxy call descriptor class. Mangled signature:
//  _clong_i_clong
class _0RL_cd_8dfcf7274d2061b7_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_8dfcf7274d2061b7_20000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::Long result;
};

void _0RL_cd_8dfcf7274d2061b7_20000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_8dfcf7274d2061b7_20000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;

}

void _0RL_cd_8dfcf7274d2061b7_20000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_8dfcf7274d2061b7_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Long&)result <<= _n;

}

const char* const _0RL_cd_8dfcf7274d2061b7_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_8dfcf7274d2061b7_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_8dfcf7274d2061b7_20000000* tcd = (_0RL_cd_8dfcf7274d2061b7_20000000*)cd;
  ComplementaresApp::_impl_DepositoAtividades* impl = (ComplementaresApp::_impl_DepositoAtividades*) svnt->_ptrToInterface(ComplementaresApp::DepositoAtividades::_PD_repoId);
  tcd->result = impl->contarHorasCadastradas(tcd->arg_0);


}

::CORBA::Long ComplementaresApp::_objref_DepositoAtividades::contarHorasCadastradas(::CORBA::Long RA)
{
  _0RL_cd_8dfcf7274d2061b7_20000000 _call_desc(_0RL_lcfn_8dfcf7274d2061b7_30000000, "contarHorasCadastradas", 23);
  _call_desc.arg_0 = RA;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for ComplementaresApp::DepositoAtividades::atividadesCadastradas

// Proxy call descriptor class. Mangled signature:
//  _cComplementaresApp_mAtividadesComplementares_i_clong
class _0RL_cd_8dfcf7274d2061b7_40000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_8dfcf7274d2061b7_40000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ComplementaresApp::AtividadesComplementares_var result;
};

void _0RL_cd_8dfcf7274d2061b7_40000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_8dfcf7274d2061b7_40000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;

}

void _0RL_cd_8dfcf7274d2061b7_40000000::marshalReturnedValues(cdrStream& _n)
{
  (const ComplementaresApp::AtividadesComplementares&) result >>= _n;

}

void _0RL_cd_8dfcf7274d2061b7_40000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new ComplementaresApp::AtividadesComplementares;
  (ComplementaresApp::AtividadesComplementares&)result <<= _n;

}

const char* const _0RL_cd_8dfcf7274d2061b7_40000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_8dfcf7274d2061b7_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_8dfcf7274d2061b7_40000000* tcd = (_0RL_cd_8dfcf7274d2061b7_40000000*)cd;
  ComplementaresApp::_impl_DepositoAtividades* impl = (ComplementaresApp::_impl_DepositoAtividades*) svnt->_ptrToInterface(ComplementaresApp::DepositoAtividades::_PD_repoId);
  tcd->result = impl->atividadesCadastradas(tcd->arg_0);


}

ComplementaresApp::AtividadesComplementares* ComplementaresApp::_objref_DepositoAtividades::atividadesCadastradas(::CORBA::Long RA)
{
  _0RL_cd_8dfcf7274d2061b7_40000000 _call_desc(_0RL_lcfn_8dfcf7274d2061b7_50000000, "atividadesCadastradas", 22);
  _call_desc.arg_0 = RA;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ComplementaresApp::DepositoAtividades::removerAtividade

// Local call call-back function.
static void
_0RL_lcfn_8dfcf7274d2061b7_60000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_8dfcf7274d2061b7_00000000* tcd = (_0RL_cd_8dfcf7274d2061b7_00000000*)cd;
  ComplementaresApp::_impl_DepositoAtividades* impl = (ComplementaresApp::_impl_DepositoAtividades*) svnt->_ptrToInterface(ComplementaresApp::DepositoAtividades::_PD_repoId);
  tcd->result = impl->removerAtividade(*tcd->arg_0);


}

::CORBA::Boolean ComplementaresApp::_objref_DepositoAtividades::removerAtividade(const ::ComplementaresApp::AtividadeComplementar& at)
{
  _0RL_cd_8dfcf7274d2061b7_00000000 _call_desc(_0RL_lcfn_8dfcf7274d2061b7_60000000, "removerAtividade", 17);
  _call_desc.arg_0 = &(::ComplementaresApp::AtividadeComplementar&) at;

  _invoke(_call_desc);
  return _call_desc.result;


}

ComplementaresApp::_pof_DepositoAtividades::~_pof_DepositoAtividades() {}


omniObjRef*
ComplementaresApp::_pof_DepositoAtividades::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::ComplementaresApp::_objref_DepositoAtividades(ior, id);
}


::CORBA::Boolean
ComplementaresApp::_pof_DepositoAtividades::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::ComplementaresApp::DepositoAtividades::_PD_repoId))
    return 1;
  
  return 0;
}

const ComplementaresApp::_pof_DepositoAtividades _the_pof_ComplementaresApp_mDepositoAtividades;

ComplementaresApp::_impl_DepositoAtividades::~_impl_DepositoAtividades() {}


::CORBA::Boolean
ComplementaresApp::_impl_DepositoAtividades::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "cadastrarAtividade")) {

    _0RL_cd_8dfcf7274d2061b7_00000000 _call_desc(_0RL_lcfn_8dfcf7274d2061b7_10000000, "cadastrarAtividade", 19, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "contarHorasCadastradas")) {

    _0RL_cd_8dfcf7274d2061b7_20000000 _call_desc(_0RL_lcfn_8dfcf7274d2061b7_30000000, "contarHorasCadastradas", 23, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "atividadesCadastradas")) {

    _0RL_cd_8dfcf7274d2061b7_40000000 _call_desc(_0RL_lcfn_8dfcf7274d2061b7_50000000, "atividadesCadastradas", 22, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "removerAtividade")) {

    _0RL_cd_8dfcf7274d2061b7_00000000 _call_desc(_0RL_lcfn_8dfcf7274d2061b7_60000000, "removerAtividade", 17, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
ComplementaresApp::_impl_DepositoAtividades::_ptrToInterface(const char* id)
{
  if (id == ::ComplementaresApp::DepositoAtividades::_PD_repoId)
    return (::ComplementaresApp::_impl_DepositoAtividades*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::ComplementaresApp::DepositoAtividades::_PD_repoId))
    return (::ComplementaresApp::_impl_DepositoAtividades*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
ComplementaresApp::_impl_DepositoAtividades::_mostDerivedRepoId()
{
  return ::ComplementaresApp::DepositoAtividades::_PD_repoId;
}

POA_ComplementaresApp::DepositoAtividades::~DepositoAtividades() {}

